postgres_db:
  driver: postgres
  host: leaderboardscoring-db
  port: 5432
  user: leaderboardscoring_admin
  password: password123
  db_name: leaderboardscoring_db
  ssl_mode: disable

path_of_migration: ./leaderboardscoring/repository/migrations