postgres_db:
  driver: postgres
  host: localhost
  port: 5432
  user: "task_admin"
  password: "password123"
  db_name: task_db
  ssl_mode: disable
  max_conns: 20
  min_conns: 5
  max_conn_lifetime: 1800
  max_conn_idle_time: 600
  health_check_period: 30

path_of_migration: ./taskapp/repository/migrations
