// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: contributor/v1/contributor.proto

package contributorpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ContributorService_GetContributor_FullMethodName = "/contributor.v1.ContributorService/GetContributor"
	ContributorService_UpdatePassword_FullMethodName = "/contributor.v1.ContributorService/UpdatePassword"
	ContributorService_VerifyPassword_FullMethodName = "/contributor.v1.ContributorService/VerifyPassword"
)

// ContributorServiceClient is the client API for ContributorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ContributorServiceClient interface {
	GetContributor(ctx context.Context, in *GetContributorRequest, opts ...grpc.CallOption) (*GetContributorResponse, error)
	UpdatePassword(ctx context.Context, in *UpdatePasswordRequest, opts ...grpc.CallOption) (*UpdatePasswordResponse, error)
	VerifyPassword(ctx context.Context, in *VerifyPasswordRequest, opts ...grpc.CallOption) (*VerifyPasswordResponse, error)
}

type contributorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewContributorServiceClient(cc grpc.ClientConnInterface) ContributorServiceClient {
	return &contributorServiceClient{cc}
}

func (c *contributorServiceClient) GetContributor(ctx context.Context, in *GetContributorRequest, opts ...grpc.CallOption) (*GetContributorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetContributorResponse)
	err := c.cc.Invoke(ctx, ContributorService_GetContributor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contributorServiceClient) UpdatePassword(ctx context.Context, in *UpdatePasswordRequest, opts ...grpc.CallOption) (*UpdatePasswordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdatePasswordResponse)
	err := c.cc.Invoke(ctx, ContributorService_UpdatePassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contributorServiceClient) VerifyPassword(ctx context.Context, in *VerifyPasswordRequest, opts ...grpc.CallOption) (*VerifyPasswordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyPasswordResponse)
	err := c.cc.Invoke(ctx, ContributorService_VerifyPassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ContributorServiceServer is the server API for ContributorService service.
// All implementations must embed UnimplementedContributorServiceServer
// for forward compatibility.
type ContributorServiceServer interface {
	GetContributor(context.Context, *GetContributorRequest) (*GetContributorResponse, error)
	UpdatePassword(context.Context, *UpdatePasswordRequest) (*UpdatePasswordResponse, error)
	VerifyPassword(context.Context, *VerifyPasswordRequest) (*VerifyPasswordResponse, error)
	mustEmbedUnimplementedContributorServiceServer()
}

// UnimplementedContributorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedContributorServiceServer struct{}

func (UnimplementedContributorServiceServer) GetContributor(context.Context, *GetContributorRequest) (*GetContributorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetContributor not implemented")
}
func (UnimplementedContributorServiceServer) UpdatePassword(context.Context, *UpdatePasswordRequest) (*UpdatePasswordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePassword not implemented")
}
func (UnimplementedContributorServiceServer) VerifyPassword(context.Context, *VerifyPasswordRequest) (*VerifyPasswordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyPassword not implemented")
}
func (UnimplementedContributorServiceServer) mustEmbedUnimplementedContributorServiceServer() {}
func (UnimplementedContributorServiceServer) testEmbeddedByValue()                            {}

// UnsafeContributorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ContributorServiceServer will
// result in compilation errors.
type UnsafeContributorServiceServer interface {
	mustEmbedUnimplementedContributorServiceServer()
}

func RegisterContributorServiceServer(s grpc.ServiceRegistrar, srv ContributorServiceServer) {
	// If the following call pancis, it indicates UnimplementedContributorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ContributorService_ServiceDesc, srv)
}

func _ContributorService_GetContributor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContributorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContributorServiceServer).GetContributor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContributorService_GetContributor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContributorServiceServer).GetContributor(ctx, req.(*GetContributorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContributorService_UpdatePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContributorServiceServer).UpdatePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContributorService_UpdatePassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContributorServiceServer).UpdatePassword(ctx, req.(*UpdatePasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContributorService_VerifyPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContributorServiceServer).VerifyPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContributorService_VerifyPassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContributorServiceServer).VerifyPassword(ctx, req.(*VerifyPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ContributorService_ServiceDesc is the grpc.ServiceDesc for ContributorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ContributorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "contributor.v1.ContributorService",
	HandlerType: (*ContributorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetContributor",
			Handler:    _ContributorService_GetContributor_Handler,
		},
		{
			MethodName: "UpdatePassword",
			Handler:    _ContributorService_UpdatePassword_Handler,
		},
		{
			MethodName: "VerifyPassword",
			Handler:    _ContributorService_VerifyPassword_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "contributor/v1/contributor.proto",
}
