postgres_db:
  driver: postgres
  host: project-db
  port: 5432
  user: project_admin
  password: password123
  db_name: project_db
  ssl_mode: disable

path_of_migration: ./projectsapp/repository/migrations
