postgres_db:
  driver: postgres
  host: localhost
  port: 5432
  user: TestDev_User
  password: 123456789AAAA
  db_name: project_db
  ssl_mode: disable

path_of_migration: ./projectapp/repository/migrations