services:
  leaderboardscoring-db:
    image: postgres:14-alpine
    container_name: leaderboardscoring-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: leaderboardscoring_db
    restart: always
    volumes:
      - leaderboardscoring-data:/var/lib/postgresql/data
    healthcheck:
      # The healthcheck also uses the variable for consistency
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d leaderboardscoring_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  leaderboardscoring-redis:
    image: redis:6.2-alpine
    container_name: leaderboardscoring-redis
    ports:
      - "6379:6379"
    restart: always

  leaderboardscoring-nats:
    image: nats:2.11.8
    container_name: nats_jetstream
    restart: unless-stopped
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - nats1:/data
    command:
      - "--name=nats1"
      - "--sd=/data"
      - "--js"
      - "--http_port=8222"
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8222/varz && nc -z localhost 4222" ]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s

volumes:
  leaderboardscoring-data:
  nats1:
