services:
  # PostgreSQL Database Service
  leaderboardscoring-db:
    image: postgres:14-alpine
    container_name: lb_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: leaderboardscoring_admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: leaderboardscoring_db
    restart: always
    volumes:
      - lb_data_db_local:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U leaderboardscoring_admin -d leaderboardscoring_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  # Redis Service
  leaderboardscoring-redis:
    image: bitnami/redis:8.0.1-debian-12-r2
    container_name: lb_redis
    ports:
      - "6379:6379"
    environment:
      - "REDIS_PASSWORD=password1999"
      - "REDIS_DAEMON_USER=redis"
      - "REDIS_RDB_POLICY_DISABLE=yes"
      - "REDIS_AOF_ENABLED=yes"
      #      - "REDIS_RDB_ENABLED=yes"
      #      - ALLOW_EMPTY_PASSWORD=yes
    restart: always
    volumes:
      - redis_data_local:/bitnami/redis/data
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "$$REDIS_PASSWORD", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redis_insight
    restart: unless-stopped
    ports:
      - "5540:5540"
    depends_on:
      - leaderboardscoring-redis

  # NATS JetStream Service
  leaderboardscoring-nats:
    image: nats:2.10-alpine
    container_name: lb_nats
    restart: unless-stopped
    ports:
      - "4222:4222" # Client port
      - "8222:8222" # Monitoring port
    volumes:
      - nats_data_local:/data
    command:
      - "--name=nats1"
      - "--sd=/data"
      - "--js"
      - "--http_port=8222"
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8222/varz && nc -z localhost 4222" ]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s

  # NATS Box for CLI and testing
  nats-box:
    image: natsio/nats-box:0.8.0
    container_name: nats_box
    depends_on:
      leaderboardscoring-nats:
        condition: service_healthy
    environment:
      - NATS_URL=nats://leaderboardscoring-nats:4222
    tty: true
    stdin_open: true

volumes:
  lb_data_db_local:
    driver: local
  nats_data_local:
    driver: local
  redis_data_local:
    driver: local
