version: '3.8'

services:
  leaderboardscoring-db:
    image: postgres:17.2-alpine
    container_name: leaderboardscoring-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: leaderboardscoring_admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: leaderboardscoring_db
    restart: always
    volumes:
      - leaderboardscoring-data:/var/lib/postgresql/data

  leaderboardscoring-redis:
    image: redis:6.2-alpine
    container_name: leaderboardscoring-redis
    ports:
      - "6379:6379"
    restart: always

  leaderboardscoring-nats:
    image: nats:2.11.8
    container_name: nats_jetstream
    restart: unless-stopped
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - nats1:/data
    command:
      - "--name=nats1"
      - "--sd=/data"
      - "--js"
      - "--http_port=8222"

volumes:
  leaderboardscoring-data:
  nats1: