server:
  port: 5001
  cors:
    allow_origins: "*"


total_shutdown_timeout: 15s

postgres_db:
  driver: postgres
  host: localhost
  port: 5433
  user: "task_admin"
  password: "password123"
  db_name: task_db
  ssl_mode: disable
  max_idle_conns: 15
  max_open_conns: 100
  conn_max_lifetime: 5

#grpc_client:
#  Host: "rankr-app-service-1"
#  port: 6003
#  type: "tcp"
#  shutdown_context_timeout: "10s"
#
#grpc_server:
#  Host: "localhost"
#  port: 6002
#  type: "tcp"

logger:
  level: "debug"
  file_path: "logs/task/service.log"
  use_local_time: true
  file_max_size_in_mb: 10
  file_max_age_in_days: 7


path_of_migration: './taskapp/repository/migrations'
