postgres_db:
  driver: postgres
  host: leaderboardstat-db  # Make sure this matches your docker service name
  port: 5432
  user: stat_admin
  password: password123
  db_name: leaderboardstat_db
  ssl_mode: disable

  pool:
    max_size: 10
    min_size: 1
    max_lifetime: "30m"
    max_idle_time: "5m"
    health_check_period: "1m"

path_of_migration: ./leaderboardstatapp/repository/migrations