shutdown_ctx_timeout: 5s
total_shutdown_timeout: 10s
http_server:
  host: ""
  port: 8090
  shutdown_context_timeout: 5s

logger:
  level: "debug"
  file_path: "logs/webhook/service.log"
  use_local_time: true
  file_max_size_in_mb: 10
  file_max_age_in_days: 7