postgres_db:
  driver: postgres
  host: contributor-db
  port: 5432
  user: contributor_admin
  password: password123 # In production, use environment variables or a secrets manager
  db_name: contributor_db
  ssl_mode: disable

path_of_migration: ./contributorapp/repository/migrations