postgres_db:
  driver: postgres
  host: localhost
  port: 5432
  user: notifapp_admin
  password: password123
  db_name: notifications
  ssl_mode: disable

path_of_migration: ./notifapp/repository/migrations