// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: leaderboardstat/v1/leaderboardstat.proto

package leaderboardstatv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LeaderboardStatService_GetContributorStats_FullMethodName = "/leaderboardstat.v1.LeaderboardStatService/GetContributorStats"
)

// LeaderboardStatServiceClient is the client API for LeaderboardStatService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LeaderboardStatServiceClient interface {
	GetContributorStats(ctx context.Context, in *GetContributorStatsRequest, opts ...grpc.CallOption) (*GetContributorStatsResponse, error)
}

type leaderboardStatServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLeaderboardStatServiceClient(cc grpc.ClientConnInterface) LeaderboardStatServiceClient {
	return &leaderboardStatServiceClient{cc}
}

func (c *leaderboardStatServiceClient) GetContributorStats(ctx context.Context, in *GetContributorStatsRequest, opts ...grpc.CallOption) (*GetContributorStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetContributorStatsResponse)
	err := c.cc.Invoke(ctx, LeaderboardStatService_GetContributorStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LeaderboardStatServiceServer is the server API for LeaderboardStatService service.
// All implementations must embed UnimplementedLeaderboardStatServiceServer
// for forward compatibility.
type LeaderboardStatServiceServer interface {
	GetContributorStats(context.Context, *GetContributorStatsRequest) (*GetContributorStatsResponse, error)
	mustEmbedUnimplementedLeaderboardStatServiceServer()
}

// UnimplementedLeaderboardStatServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLeaderboardStatServiceServer struct{}

func (UnimplementedLeaderboardStatServiceServer) GetContributorStats(context.Context, *GetContributorStatsRequest) (*GetContributorStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetContributorStats not implemented")
}
func (UnimplementedLeaderboardStatServiceServer) mustEmbedUnimplementedLeaderboardStatServiceServer() {
}
func (UnimplementedLeaderboardStatServiceServer) testEmbeddedByValue() {}

// UnsafeLeaderboardStatServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LeaderboardStatServiceServer will
// result in compilation errors.
type UnsafeLeaderboardStatServiceServer interface {
	mustEmbedUnimplementedLeaderboardStatServiceServer()
}

func RegisterLeaderboardStatServiceServer(s grpc.ServiceRegistrar, srv LeaderboardStatServiceServer) {
	// If the following call pancis, it indicates UnimplementedLeaderboardStatServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LeaderboardStatService_ServiceDesc, srv)
}

func _LeaderboardStatService_GetContributorStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContributorStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeaderboardStatServiceServer).GetContributorStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LeaderboardStatService_GetContributorStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeaderboardStatServiceServer).GetContributorStats(ctx, req.(*GetContributorStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LeaderboardStatService_ServiceDesc is the grpc.ServiceDesc for LeaderboardStatService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LeaderboardStatService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "leaderboardstat.v1.LeaderboardStatService",
	HandlerType: (*LeaderboardStatServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetContributorStats",
			Handler:    _LeaderboardStatService_GetContributorStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "leaderboardstat/v1/leaderboardstat.proto",
}
