// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.5
// source: leaderboardscoring.proto

package leaderboardscoringpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LeaderboardScoringService_GetLeaderboard_FullMethodName = "/leaderboardscoring.v1.LeaderboardScoringService/GetLeaderboard"
)

// LeaderboardScoringServiceClient is the client API for LeaderboardScoringService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LeaderboardScoringServiceClient interface {
	// Fetches a single snapshot of the leaderboard with pagination.
	// Real-time updates are handled by Centrifugo.
	GetLeaderboard(ctx context.Context, in *GetLeaderboardRequest, opts ...grpc.CallOption) (*GetLeaderboardResponse, error)
}

type leaderboardScoringServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLeaderboardScoringServiceClient(cc grpc.ClientConnInterface) LeaderboardScoringServiceClient {
	return &leaderboardScoringServiceClient{cc}
}

func (c *leaderboardScoringServiceClient) GetLeaderboard(ctx context.Context, in *GetLeaderboardRequest, opts ...grpc.CallOption) (*GetLeaderboardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLeaderboardResponse)
	err := c.cc.Invoke(ctx, LeaderboardScoringService_GetLeaderboard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LeaderboardScoringServiceServer is the server API for LeaderboardScoringService service.
// All implementations must embed UnimplementedLeaderboardScoringServiceServer
// for forward compatibility.
type LeaderboardScoringServiceServer interface {
	// Fetches a single snapshot of the leaderboard with pagination.
	// Real-time updates are handled by Centrifugo.
	GetLeaderboard(context.Context, *GetLeaderboardRequest) (*GetLeaderboardResponse, error)
	mustEmbedUnimplementedLeaderboardScoringServiceServer()
}

// UnimplementedLeaderboardScoringServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLeaderboardScoringServiceServer struct{}

func (UnimplementedLeaderboardScoringServiceServer) GetLeaderboard(context.Context, *GetLeaderboardRequest) (*GetLeaderboardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLeaderboard not implemented")
}
func (UnimplementedLeaderboardScoringServiceServer) mustEmbedUnimplementedLeaderboardScoringServiceServer() {
}
func (UnimplementedLeaderboardScoringServiceServer) testEmbeddedByValue() {}

// UnsafeLeaderboardScoringServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LeaderboardScoringServiceServer will
// result in compilation errors.
type UnsafeLeaderboardScoringServiceServer interface {
	mustEmbedUnimplementedLeaderboardScoringServiceServer()
}

func RegisterLeaderboardScoringServiceServer(s grpc.ServiceRegistrar, srv LeaderboardScoringServiceServer) {
	// If the following call pancis, it indicates UnimplementedLeaderboardScoringServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LeaderboardScoringService_ServiceDesc, srv)
}

func _LeaderboardScoringService_GetLeaderboard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLeaderboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeaderboardScoringServiceServer).GetLeaderboard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LeaderboardScoringService_GetLeaderboard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeaderboardScoringServiceServer).GetLeaderboard(ctx, req.(*GetLeaderboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LeaderboardScoringService_ServiceDesc is the grpc.ServiceDesc for LeaderboardScoringService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LeaderboardScoringService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "leaderboardscoring.v1.LeaderboardScoringService",
	HandlerType: (*LeaderboardScoringServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLeaderboard",
			Handler:    _LeaderboardScoringService_GetLeaderboard_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "leaderboardscoring.proto",
}
