// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.5
// source: leaderboardscoring.proto

package leaderboardscoringpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enum to define standard timeframes for requests, preventing typos.
type Timeframe int32

const (
	Timeframe_TIMEFRAME_UNSPECIFIED Timeframe = 0
	Timeframe_TIMEFRAME_ALL_TIME    Timeframe = 1
	Timeframe_TIMEFRAME_YEARLY      Timeframe = 2 // Represents the last year
	Timeframe_TIMEFRAME_MONTHLY     Timeframe = 3 // Represents the last month
	Timeframe_TIMEFRAME_WEEKLY      Timeframe = 4 // Represents the last week
	Timeframe_TIMEFRAME_DAILY       Timeframe = 5 // Represents the last day
)

// Enum value maps for Timeframe.
var (
	Timeframe_name = map[int32]string{
		0: "TIMEFRAME_UNSPECIFIED",
		1: "TIMEFRAME_ALL_TIME",
		2: "TIMEFRAME_YEARLY",
		3: "TIMEFRAME_MONTHLY",
		4: "TIMEFRAME_WEEKLY",
		5: "TIMEFRAME_DAILY",
	}
	Timeframe_value = map[string]int32{
		"TIMEFRAME_UNSPECIFIED": 0,
		"TIMEFRAME_ALL_TIME":    1,
		"TIMEFRAME_YEARLY":      2,
		"TIMEFRAME_MONTHLY":     3,
		"TIMEFRAME_WEEKLY":      4,
		"TIMEFRAME_DAILY":       5,
	}
)

func (x Timeframe) Enum() *Timeframe {
	p := new(Timeframe)
	*p = x
	return p
}

func (x Timeframe) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Timeframe) Descriptor() protoreflect.EnumDescriptor {
	return file_leaderboardscoring_proto_enumTypes[0].Descriptor()
}

func (Timeframe) Type() protoreflect.EnumType {
	return &file_leaderboardscoring_proto_enumTypes[0]
}

func (x Timeframe) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Timeframe.Descriptor instead.
func (Timeframe) EnumDescriptor() ([]byte, []int) {
	return file_leaderboardscoring_proto_rawDescGZIP(), []int{0}
}

// Represents a single entry in any leaderboard.
type LeaderboardRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rank          uint64                 `protobuf:"varint,1,opt,name=rank,proto3" json:"rank,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Score         uint64                 `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaderboardRow) Reset() {
	*x = LeaderboardRow{}
	mi := &file_leaderboardscoring_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderboardRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderboardRow) ProtoMessage() {}

func (x *LeaderboardRow) ProtoReflect() protoreflect.Message {
	mi := &file_leaderboardscoring_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderboardRow.ProtoReflect.Descriptor instead.
func (*LeaderboardRow) Descriptor() ([]byte, []int) {
	return file_leaderboardscoring_proto_rawDescGZIP(), []int{0}
}

func (x *LeaderboardRow) GetRank() uint64 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *LeaderboardRow) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LeaderboardRow) GetScore() uint64 {
	if x != nil {
		return x.Score
	}
	return 0
}

// A standard RPC for fetching a snapshot of the leaderboard.
// The server will automatically determine the correct period (e.g., current month for MONTHLY).
type GetLeaderboardRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Timeframe Timeframe              `protobuf:"varint,1,opt,name=timeframe,proto3,enum=leaderboardscoring.v1.Timeframe" json:"timeframe,omitempty"`
	ProjectId *string                `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3,oneof" json:"project_id,omitempty"` // If provided, fetches a per-project leaderboard.
	// Pagination parameters
	PageSize      int32 `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // How many rows to return.
	Offset        int32 `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`                     // Where to start from (e.g., 0 for the first page, 50 for the second).
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLeaderboardRequest) Reset() {
	*x = GetLeaderboardRequest{}
	mi := &file_leaderboardscoring_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLeaderboardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLeaderboardRequest) ProtoMessage() {}

func (x *GetLeaderboardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_leaderboardscoring_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLeaderboardRequest.ProtoReflect.Descriptor instead.
func (*GetLeaderboardRequest) Descriptor() ([]byte, []int) {
	return file_leaderboardscoring_proto_rawDescGZIP(), []int{1}
}

func (x *GetLeaderboardRequest) GetTimeframe() Timeframe {
	if x != nil {
		return x.Timeframe
	}
	return Timeframe_TIMEFRAME_UNSPECIFIED
}

func (x *GetLeaderboardRequest) GetProjectId() string {
	if x != nil && x.ProjectId != nil {
		return *x.ProjectId
	}
	return ""
}

func (x *GetLeaderboardRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetLeaderboardRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetLeaderboardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timeframe     Timeframe              `protobuf:"varint,1,opt,name=timeframe,proto3,enum=leaderboardscoring.v1.Timeframe" json:"timeframe,omitempty"`
	ProjectId     *string                `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3,oneof" json:"project_id,omitempty"`
	Rows          []*LeaderboardRow      `protobuf:"bytes,3,rep,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLeaderboardResponse) Reset() {
	*x = GetLeaderboardResponse{}
	mi := &file_leaderboardscoring_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLeaderboardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLeaderboardResponse) ProtoMessage() {}

func (x *GetLeaderboardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_leaderboardscoring_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLeaderboardResponse.ProtoReflect.Descriptor instead.
func (*GetLeaderboardResponse) Descriptor() ([]byte, []int) {
	return file_leaderboardscoring_proto_rawDescGZIP(), []int{2}
}

func (x *GetLeaderboardResponse) GetTimeframe() Timeframe {
	if x != nil {
		return x.Timeframe
	}
	return Timeframe_TIMEFRAME_UNSPECIFIED
}

func (x *GetLeaderboardResponse) GetProjectId() string {
	if x != nil && x.ProjectId != nil {
		return *x.ProjectId
	}
	return ""
}

func (x *GetLeaderboardResponse) GetRows() []*LeaderboardRow {
	if x != nil {
		return x.Rows
	}
	return nil
}

var File_leaderboardscoring_proto protoreflect.FileDescriptor

const file_leaderboardscoring_proto_rawDesc = "" +
	"\n" +
	"\x18leaderboardscoring.proto\x12\x15leaderboardscoring.v1\"S\n" +
	"\x0eLeaderboardRow\x12\x12\n" +
	"\x04rank\x18\x01 \x01(\x04R\x04rank\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x04R\x05score\"\xbf\x01\n" +
	"\x15GetLeaderboardRequest\x12>\n" +
	"\ttimeframe\x18\x01 \x01(\x0e2 .leaderboardscoring.v1.TimeframeR\ttimeframe\x12\"\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tH\x00R\tprojectId\x88\x01\x01\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offsetB\r\n" +
	"\v_project_id\"\xc6\x01\n" +
	"\x16GetLeaderboardResponse\x12>\n" +
	"\ttimeframe\x18\x01 \x01(\x0e2 .leaderboardscoring.v1.TimeframeR\ttimeframe\x12\"\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tH\x00R\tprojectId\x88\x01\x01\x129\n" +
	"\x04rows\x18\x03 \x03(\v2%.leaderboardscoring.v1.LeaderboardRowR\x04rowsB\r\n" +
	"\v_project_id*\x96\x01\n" +
	"\tTimeframe\x12\x19\n" +
	"\x15TIMEFRAME_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12TIMEFRAME_ALL_TIME\x10\x01\x12\x14\n" +
	"\x10TIMEFRAME_YEARLY\x10\x02\x12\x15\n" +
	"\x11TIMEFRAME_MONTHLY\x10\x03\x12\x14\n" +
	"\x10TIMEFRAME_WEEKLY\x10\x04\x12\x13\n" +
	"\x0fTIMEFRAME_DAILY\x10\x052\x8a\x01\n" +
	"\x19LeaderboardScoringService\x12m\n" +
	"\x0eGetLeaderboard\x12,.leaderboardscoring.v1.GetLeaderboardRequest\x1a-.leaderboardscoring.v1.GetLeaderboardResponseB&Z$protobuf/golang/leaderboardscoringpbb\x06proto3"

var (
	file_leaderboardscoring_proto_rawDescOnce sync.Once
	file_leaderboardscoring_proto_rawDescData []byte
)

func file_leaderboardscoring_proto_rawDescGZIP() []byte {
	file_leaderboardscoring_proto_rawDescOnce.Do(func() {
		file_leaderboardscoring_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_leaderboardscoring_proto_rawDesc), len(file_leaderboardscoring_proto_rawDesc)))
	})
	return file_leaderboardscoring_proto_rawDescData
}

var file_leaderboardscoring_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_leaderboardscoring_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_leaderboardscoring_proto_goTypes = []any{
	(Timeframe)(0),                 // 0: leaderboardscoring.v1.Timeframe
	(*LeaderboardRow)(nil),         // 1: leaderboardscoring.v1.LeaderboardRow
	(*GetLeaderboardRequest)(nil),  // 2: leaderboardscoring.v1.GetLeaderboardRequest
	(*GetLeaderboardResponse)(nil), // 3: leaderboardscoring.v1.GetLeaderboardResponse
}
var file_leaderboardscoring_proto_depIdxs = []int32{
	0, // 0: leaderboardscoring.v1.GetLeaderboardRequest.timeframe:type_name -> leaderboardscoring.v1.Timeframe
	0, // 1: leaderboardscoring.v1.GetLeaderboardResponse.timeframe:type_name -> leaderboardscoring.v1.Timeframe
	1, // 2: leaderboardscoring.v1.GetLeaderboardResponse.rows:type_name -> leaderboardscoring.v1.LeaderboardRow
	2, // 3: leaderboardscoring.v1.LeaderboardScoringService.GetLeaderboard:input_type -> leaderboardscoring.v1.GetLeaderboardRequest
	3, // 4: leaderboardscoring.v1.LeaderboardScoringService.GetLeaderboard:output_type -> leaderboardscoring.v1.GetLeaderboardResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_leaderboardscoring_proto_init() }
func file_leaderboardscoring_proto_init() {
	if File_leaderboardscoring_proto != nil {
		return
	}
	file_leaderboardscoring_proto_msgTypes[1].OneofWrappers = []any{}
	file_leaderboardscoring_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_leaderboardscoring_proto_rawDesc), len(file_leaderboardscoring_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_leaderboardscoring_proto_goTypes,
		DependencyIndexes: file_leaderboardscoring_proto_depIdxs,
		EnumInfos:         file_leaderboardscoring_proto_enumTypes,
		MessageInfos:      file_leaderboardscoring_proto_msgTypes,
	}.Build()
	File_leaderboardscoring_proto = out.File
	file_leaderboardscoring_proto_goTypes = nil
	file_leaderboardscoring_proto_depIdxs = nil
}
