postgres_db:
  host: "localhost"
  port: 5436
  user: "webhook_admin"
  password: "password123"
  db_name: "webhook_db"
  ssl_mode: "disable"
  max_conns: 100
  min_conns: 2
  max_conn_lifetime: 3600
  max_conn_idle_time: 300
  health_check_period: 30

path_of_migration: "./webhookapp/repository/migrations"