postgres_db:
  driver: postgres
  host: localhost
  port: 5432
  user: stat_admin
  password: password123
  db_name: leaderboardstat_db
  ssl_mode: disable

path_of_migration: ./leaderboardstatapp/repository/postgres/migrations