name: CI RANKR

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.x'
          check-latest: true
          cache: true

      - name: Go mod tidy & download
        run: |
          go mod tidy
          go mod download

      - name: Lint (non-blocking)
        uses: golangci/golangci-lint-action@v8
        continue-on-error: true
        with:
          version: v2.4.0
          args: >
            --timeout=5m
            --issues-exit-code=0
            --out-format=github-actions

      - name: Test
        run: go test ./... -v -coverprofile=coverage.out

      - name: Build
        run: go build -v ./...
