name: Update Go Modules on New Package

on:
  push:
    branches: [ main ]
    paths:
      - 'pkg/**'      # Only watch package directories
      - 'cmd/**'      # Only watch command directories
      - 'services/**' # Only watch service directories
      - 'internal/**' # Only watch internal directories
      - '!go.mod'     # EXCLUDE go.mod - important!
      - '!go.sum'     # EXCLUDE go.sum - important!

jobs:
  update-go-modules:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}  # Add this!

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.25.0'

      - name: Generate go.mod and go.sum
        run: |
          # Initialize go.mod if it doesn't exist
          if [ ! -f go.mod ]; then
            go mod init github.com/gocasters/rankr
          fi
          
          # Tidy modules to generate go.mod and go.sum
          go mod tidy
          
          # Check if files were modified
          if git diff --name-only --exit-code; then
            echo "No changes to go.mod or go.sum"
          else
            echo "go.mod and/or go.sum updated"
          
            # Configure git
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
          
            # Commit and push changes
            git add go.mod go.sum
            git commit -m "ci: auto-update go.mod and go.sum"
            git push
          fi